PATCH http://localhost:3000/api/scrums?id=<scrumId>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGQyZDRkZWQ5NjRjYTNhOWFkYWQ1NiIsImlhdCI6MTczNzMwNjA0MSwiZXhwIjoxNzM3MzkyNDQxfQ.LIwOwrrfQfEJ90HqlAY4_BHLHFQj3-7LBof4W0JF654
Content-Type: application/json

{
  "name": "Updated Scrum Name",
  "description": "Updated Scrum Description"
}

###
POST http://localhost:3000/api/scrums/task?id=<scrumId>
Authorization: Bearer <your_jwt_token>
Content-Type: application/json

{
  "taskId": "64b123abcde67890f1234567"
}

###
DELETE http://localhost:3000/api/scrums/task?id=<scrumId>
Authorization: Bearer <your_jwt_token>
Content-Type: application/json

{
  "taskId": "64b123abcde67890f1234567"
}


###
DELETE http://localhost:3000/api/scrums?id=<scrumId>
Authorization: Bearer <your_jwt_token>


###
GET http://localhost:3000/api/scrums?projectId=678d403a07b5d804c8997c2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGQ1MWUyYmQ4MmYzMzZjNWZmMTYwOCIsImlhdCI6MTczNzY1NDU0MCwiZXhwIjoxNzM3NzQwOTQwfQ.Asoz3QFE0B7v0E_HEakFtvXS-7qeY35dDx3eCuYrFZw
Content-Type: application/json


###
POST http://localhost:3000/api/scrums
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGQ1MWUyYmQ4MmYzMzZjNWZmMTYwOCIsImlhdCI6MTczNzY1NDU0MCwiZXhwIjoxNzM3NzQwOTQwfQ.Asoz3QFE0B7v0E_HEakFtvXS-7qeY35dDx3eCuYrFZw
Content-Type: application/json

{
  "id":"6792ad13ee2cbb2a857008fd",
  "name": "Scrum Name 1",
  "description": "Scrum Description 1",
  "stage": "to-do",
  "createdBy": "678d51e2bd82f336c5ff1608",
  "project": "678d403a07b5d804c8997c2a"
}